-- Dennis Nwanevu Chong Ochulor - 22472393
-- Inserts values into Sport table
-- Some valeus are fake as the real values only take up 45 rows

INSERT INTO Sport VALUES('ARC', 'Archery'),
('GAR', 'Artistic Gymnastics'),
('SWA', 'Artistic Swimming'),
('ATH', 'Athletics'),
('BDM', 'Badminton'),
('BKB', 'Basketball'),
('BK3', '3x3 Basketball'),
('VBV', 'Beach Volleyball'),
('BOX', 'Boxing'),
('BKG', 'Breaking'),
('CSL', 'Canoe Slalom'),
('CSP', 'Canoe Sprint'),
('BMF', 'Cycling BMX Freestyle'),
('BMX', 'Cycling BMX Racing'),
('MTB', 'Cycling Mountain Bike'),
('CRD', 'Cycling Road'),
('CTR', 'Cycling Track'),
('DIV', 'Diving'),
('EQU', 'Equestrian'),
('FEN', 'Fencing'),
('FBL', 'Football'),
('GLF', 'Golf'),
('HBL', 'Handball'),
('HOC', 'Hockey'),
('JUD', 'Judo'),
('OWS', 'Marathon Swimming'),
('MPN', 'Modern Pentathlon'),
('GRY', 'Rhythmic Gymnastics'),
('ROW', 'Rowing'),
('RU7', 'Rugby Sevens'),
('SAL', 'Sailing'),
('SHO', 'Shooting'),
('SKB', 'Skateboarding'),
('CLB', 'Sport Climbing'),
('SRF', 'Surfing'),
('SWM', 'Swimming'),
('TTE', 'Table Tennis'),
('TKW', 'Taekwondo'),
('TEN', 'Tennis'),
('GTR', 'Trampoline Gymnastics'),
('TRI', 'Triathlon'),
('VVO', 'Volleyball'),
('WPO', 'Water Polo'),
('WLF', 'Weightlifting'),
('WRE', 'Wrestling'),
('ZAA', 'Fake Sport AA'),
('ZAB', 'Fake Sport AB'),
('ZAC', 'Fake Sport AC'),
('ZAD', 'Fake Sport AD'),
('ZAE', 'Fake Sport AE'),
('ZAF', 'Fake Sport AF'),
('ZAG', 'Fake Sport AG'),
('ZAH', 'Fake Sport AH'),
('ZAI', 'Fake Sport AI'),
('ZAJ', 'Fake Sport AJ'),
('ZAK', 'Fake Sport AK'),
('ZAL', 'Fake Sport AL'),
('ZAM', 'Fake Sport AM'),
('ZAN', 'Fake Sport AN'),
('ZAO', 'Fake Sport AO'),
('ZAP', 'Fake Sport AP'),
('ZAQ', 'Fake Sport AQ'),
('ZAR', 'Fake Sport AR'),
('ZAS', 'Fake Sport AS'),
('ZAT', 'Fake Sport AT'),
('ZAU', 'Fake Sport AU'),
('ZAV', 'Fake Sport AV'),
('ZAW', 'Fake Sport AW'),
('ZAX', 'Fake Sport AX'),
('ZAY', 'Fake Sport AY'),
('ZAZ', 'Fake Sport AZ'),
('ZBA', 'Fake Sport BA'),
('ZBB', 'Fake Sport BB'),
('ZBC', 'Fake Sport BC'),
('ZBD', 'Fake Sport BD'),
('ZBE', 'Fake Sport BE'),
('ZBF', 'Fake Sport BF'),
('ZBG', 'Fake Sport BG'),
('ZBH', 'Fake Sport BH'),
('ZBI', 'Fake Sport BI'),
('ZBJ', 'Fake Sport BJ'),
('ZBK', 'Fake Sport BK'),
('ZBL', 'Fake Sport BL'),
('ZBM', 'Fake Sport BM'),
('ZBN', 'Fake Sport BN'),
('ZBO', 'Fake Sport BO'),
('ZBP', 'Fake Sport BP'),
('ZBQ', 'Fake Sport BQ'),
('ZBR', 'Fake Sport BR'),
('ZBS', 'Fake Sport BS'),
('ZBT', 'Fake Sport BT'),
('ZBU', 'Fake Sport BU'),
('ZBV', 'Fake Sport BV'),
('ZBW', 'Fake Sport BW'),
('ZBX', 'Fake Sport BX'),
('ZBY', 'Fake Sport BY'),
('ZBZ', 'Fake Sport BZ'),
('ZCA', 'Fake Sport CA'),
('ZCB', 'Fake Sport CB'),
('ZCC', 'Fake Sport CC'),
('ZCD', 'Fake Sport CD'),
('ZCE', 'Fake Sport CE'),
('ZCF', 'Fake Sport CF'),
('ZCG', 'Fake Sport CG'),
('ZCH', 'Fake Sport CH'),
('ZCI', 'Fake Sport CI'),
('ZCJ', 'Fake Sport CJ'),
('ZCK', 'Fake Sport CK'),
('ZCL', 'Fake Sport CL'),
('ZCM', 'Fake Sport CM'),
('ZCN', 'Fake Sport CN'),
('ZCO', 'Fake Sport CO'),
('ZCP', 'Fake Sport CP'),
('ZCQ', 'Fake Sport CQ'),
('ZCR', 'Fake Sport CR'),
('ZCS', 'Fake Sport CS'),
('ZCT', 'Fake Sport CT'),
('ZCU', 'Fake Sport CU'),
('ZCV', 'Fake Sport CV'),
('ZCW', 'Fake Sport CW'),
('ZCX', 'Fake Sport CX'),
('ZCY', 'Fake Sport CY'),
('ZCZ', 'Fake Sport CZ'),
('ZDA', 'Fake Sport DA'),
('ZDB', 'Fake Sport DB'),
('ZDC', 'Fake Sport DC'),
('ZDD', 'Fake Sport DD'),
('ZDE', 'Fake Sport DE'),
('ZDF', 'Fake Sport DF'),
('ZDG', 'Fake Sport DG'),
('ZDH', 'Fake Sport DH'),
('ZDI', 'Fake Sport DI'),
('ZDJ', 'Fake Sport DJ'),
('ZDK', 'Fake Sport DK'),
('ZDL', 'Fake Sport DL'),
('ZDM', 'Fake Sport DM'),
('ZDN', 'Fake Sport DN'),
('ZDO', 'Fake Sport DO'),
('ZDP', 'Fake Sport DP'),
('ZDQ', 'Fake Sport DQ'),
('ZDR', 'Fake Sport DR'),
('ZDS', 'Fake Sport DS'),
('ZDT', 'Fake Sport DT'),
('ZDU', 'Fake Sport DU'),
('ZDV', 'Fake Sport DV'),
('ZDW', 'Fake Sport DW'),
('ZDX', 'Fake Sport DX'),
('ZDY', 'Fake Sport DY'),
('ZDZ', 'Fake Sport DZ'),
('ZEA', 'Fake Sport EA'),
('ZEB', 'Fake Sport EB'),
('ZEC', 'Fake Sport EC'),
('ZED', 'Fake Sport ED'),
('ZEE', 'Fake Sport EE'),
('ZEF', 'Fake Sport EF'),
('ZEG', 'Fake Sport EG'),
('ZEH', 'Fake Sport EH'),
('ZEI', 'Fake Sport EI'),
('ZEJ', 'Fake Sport EJ'),
('ZEK', 'Fake Sport EK'),
('ZEL', 'Fake Sport EL'),
('ZEM', 'Fake Sport EM'),
('ZEN', 'Fake Sport EN'),
('ZEO', 'Fake Sport EO'),
('ZEP', 'Fake Sport EP'),
('ZEQ', 'Fake Sport EQ'),
('ZER', 'Fake Sport ER'),
('ZES', 'Fake Sport ES'),
('ZET', 'Fake Sport ET'),
('ZEU', 'Fake Sport EU'),
('ZEV', 'Fake Sport EV'),
('ZEW', 'Fake Sport EW'),
('ZEX', 'Fake Sport EX'),
('ZEY', 'Fake Sport EY'),
('ZEZ', 'Fake Sport EZ'),
('ZFA', 'Fake Sport FA'),
('ZFB', 'Fake Sport FB'),
('ZFC', 'Fake Sport FC'),
('ZFD', 'Fake Sport FD'),
('ZFE', 'Fake Sport FE'),
('ZFF', 'Fake Sport FF'),
('ZFG', 'Fake Sport FG'),
('ZFH', 'Fake Sport FH'),
('ZFI', 'Fake Sport FI'),
('ZFJ', 'Fake Sport FJ'),
('ZFK', 'Fake Sport FK'),
('ZFL', 'Fake Sport FL'),
('ZFM', 'Fake Sport FM'),
('ZFN', 'Fake Sport FN'),
('ZFO', 'Fake Sport FO'),
('ZFP', 'Fake Sport FP'),
('ZFQ', 'Fake Sport FQ'),
('ZFR', 'Fake Sport FR'),
('ZFS', 'Fake Sport FS'),
('ZFT', 'Fake Sport FT'),
('ZFU', 'Fake Sport FU'),
('ZFV', 'Fake Sport FV'),
('ZFW', 'Fake Sport FW'),
('ZFX', 'Fake Sport FX'),
('ZFY', 'Fake Sport FY'),
('ZFZ', 'Fake Sport FZ'),
('ZGA', 'Fake Sport GA'),
('ZGB', 'Fake Sport GB'),
('ZGC', 'Fake Sport GC'),
('ZGD', 'Fake Sport GD'),
('ZGE', 'Fake Sport GE'),
('ZGF', 'Fake Sport GF'),
('ZGG', 'Fake Sport GG'),
('ZGH', 'Fake Sport GH'),
('ZGI', 'Fake Sport GI'),
('ZGJ', 'Fake Sport GJ'),
('ZGK', 'Fake Sport GK'),
('ZGL', 'Fake Sport GL'),
('ZGM', 'Fake Sport GM'),
('ZGN', 'Fake Sport GN'),
('ZGO', 'Fake Sport GO'),
('ZGP', 'Fake Sport GP'),
('ZGQ', 'Fake Sport GQ'),
('ZGR', 'Fake Sport GR'),
('ZGS', 'Fake Sport GS'),
('ZGT', 'Fake Sport GT'),
('ZGU', 'Fake Sport GU'),
('ZGV', 'Fake Sport GV'),
('ZGW', 'Fake Sport GW'),
('ZGX', 'Fake Sport GX'),
('ZGY', 'Fake Sport GY'),
('ZGZ', 'Fake Sport GZ'),
('ZHA', 'Fake Sport HA'),
('ZHB', 'Fake Sport HB'),
('ZHC', 'Fake Sport HC'),
('ZHD', 'Fake Sport HD'),
('ZHE', 'Fake Sport HE'),
('ZHF', 'Fake Sport HF'),
('ZHG', 'Fake Sport HG'),
('ZHH', 'Fake Sport HH'),
('ZHI', 'Fake Sport HI'),
('ZHJ', 'Fake Sport HJ'),
('ZHK', 'Fake Sport HK'),
('ZHL', 'Fake Sport HL'),
('ZHM', 'Fake Sport HM'),
('ZHN', 'Fake Sport HN'),
('ZHO', 'Fake Sport HO'),
('ZHP', 'Fake Sport HP'),
('ZHQ', 'Fake Sport HQ'),
('ZHR', 'Fake Sport HR'),
('ZHS', 'Fake Sport HS'),
('ZHT', 'Fake Sport HT'),
('ZHU', 'Fake Sport HU'),
('ZHV', 'Fake Sport HV'),
('ZHW', 'Fake Sport HW'),
('ZHX', 'Fake Sport HX'),
('ZHY', 'Fake Sport HY'),
('ZHZ', 'Fake Sport HZ'),
('ZIA', 'Fake Sport IA'),
('ZIB', 'Fake Sport IB'),
('ZIC', 'Fake Sport IC'),
('ZID', 'Fake Sport ID'),
('ZIE', 'Fake Sport IE'),
('ZIF', 'Fake Sport IF'),
('ZIG', 'Fake Sport IG'),
('ZIH', 'Fake Sport IH'),
('ZII', 'Fake Sport II'),
('ZIJ', 'Fake Sport IJ'),
('ZIK', 'Fake Sport IK'),
('ZIL', 'Fake Sport IL'),
('ZIM', 'Fake Sport IM'),
('ZIN', 'Fake Sport IN'),
('ZIO', 'Fake Sport IO'),
('ZIP', 'Fake Sport IP'),
('ZIQ', 'Fake Sport IQ'),
('ZIR', 'Fake Sport IR'),
('ZIS', 'Fake Sport IS'),
('ZIT', 'Fake Sport IT'),
('ZIU', 'Fake Sport IU'),
('ZIV', 'Fake Sport IV'),
('ZIW', 'Fake Sport IW'),
('ZIX', 'Fake Sport IX'),
('ZIY', 'Fake Sport IY'),
('ZIZ', 'Fake Sport IZ'),
('ZJA', 'Fake Sport JA'),
('ZJB', 'Fake Sport JB'),
('ZJC', 'Fake Sport JC'),
('ZJD', 'Fake Sport JD'),
('ZJE', 'Fake Sport JE'),
('ZJF', 'Fake Sport JF'),
('ZJG', 'Fake Sport JG'),
('ZJH', 'Fake Sport JH'),
('ZJI', 'Fake Sport JI'),
('ZJJ', 'Fake Sport JJ'),
('ZJK', 'Fake Sport JK'),
('ZJL', 'Fake Sport JL'),
('ZJM', 'Fake Sport JM'),
('ZJN', 'Fake Sport JN'),
('ZJO', 'Fake Sport JO'),
('ZJP', 'Fake Sport JP'),
('ZJQ', 'Fake Sport JQ'),
('ZJR', 'Fake Sport JR'),
('ZJS', 'Fake Sport JS'),
('ZJT', 'Fake Sport JT'),
('ZJU', 'Fake Sport JU'),
('ZJV', 'Fake Sport JV'),
('ZJW', 'Fake Sport JW'),
('ZJX', 'Fake Sport JX'),
('ZJY', 'Fake Sport JY'),
('ZJZ', 'Fake Sport JZ'),
('ZKA', 'Fake Sport KA'),
('ZKB', 'Fake Sport KB'),
('ZKC', 'Fake Sport KC'),
('ZKD', 'Fake Sport KD'),
('ZKE', 'Fake Sport KE'),
('ZKF', 'Fake Sport KF'),
('ZKG', 'Fake Sport KG'),
('ZKH', 'Fake Sport KH'),
('ZKI', 'Fake Sport KI'),
('ZKJ', 'Fake Sport KJ'),
('ZKK', 'Fake Sport KK'),
('ZKL', 'Fake Sport KL'),
('ZKM', 'Fake Sport KM'),
('ZKN', 'Fake Sport KN'),
('ZKO', 'Fake Sport KO'),
('ZKP', 'Fake Sport KP'),
('ZKQ', 'Fake Sport KQ'),
('ZKR', 'Fake Sport KR'),
('ZKS', 'Fake Sport KS'),
('ZKT', 'Fake Sport KT'),
('ZKU', 'Fake Sport KU'),
('ZKV', 'Fake Sport KV'),
('ZKW', 'Fake Sport KW'),
('ZKX', 'Fake Sport KX'),
('ZKY', 'Fake Sport KY'),
('ZKZ', 'Fake Sport KZ');

