-- Dennis Nwanevu Chong Ochulor - 22472393
-- Inserts values into Venue table
-- Some values are fake because the real data only takes up 40 rows

INSERT INTO Venue VALUES('STE', 'Geoffroy-Guichard Stadium', '2024-07-25 13:00:00', '2024-07-31 19:00:00'),
('PDP', 'Parc des Princes', '2024-07-25 13:00:00', '2024-08-10 18:30:00'),
('STA', 'Stade de France', '2024-07-24 13:30:00', '2024-08-10 20:30:00'),
('NIC', 'Nice Stadium', '2024-07-25 15:00:00', '2024-08-31 21:00:00'),
('NAN', 'La Beaujoire Stadium', '2024-07-25 15:00:00', '2024-08-08 18:00:00'),
('LYO', 'Lyon Stadium', '2024-07-25 17:00:00', '2024-08-09 16:00:00'),
('BOR', 'Bordeaux Stadium', '2024-07-25 17:00:00', '2024-08-02 21:59:00'),
('MRS', 'Marseille Stadium', '2024-07-25 19:00:00', '2024-08-06 21:59:00'),
('SP6', 'South Paris Arena 6', NULL, NULL),
('INV', 'Invalides', '2024-07-25 07:30:00', '2024-08-04 13:20:00'),
('CTX', 'Chateauroux Shooting Ctr', NULL, NULL),
('CPL', 'La Chapelle Arena', NULL, NULL),
('VN1', 'Nautical St - Flat water', NULL, NULL),
('SP1', 'South Paris Arena 1', NULL, NULL),
('VER', 'Ch�teau de Versailles', '2024-07-27 07:30:00', '2024-08-11 11:30:00'),
('GRP', 'Grand Palais', '2024-07-27 08:00:00', '2024-08-10 21:00:00'),
('YDM', 'Yves-du-Manoir Stadium', '2024-07-27 08:00:00', '2024-08-09 20:30:00'),
('CDM', 'Champ-de-Mars Arena', NULL, NULL),
('BCY', 'Bercy Arena', '2024-07-27 09:00:00', '2024-08-11 16:00:00'),
('LIL', 'Pierre Mauroy Stadium', '2024-07-27 09:00:00', '2024-08-11 14:00:00'),
('AQC', 'Aquatics Centre', '2024-07-27 09:00:00', '2024-08-10 20:00:00'),
('DEF', 'Paris La Defense Arena', '2024-07-27 09:00:00', '2024-08-11 13:50:00'),
('RGA', 'Roland-Garros Stadium', NULL, NULL),
('EIF', 'Eiffel Tower Stadium', '2024-07-27 12:00:00', '2024-08-10 21:59:00'),
('ALX', 'Pont Alexandre III', '2024-07-30 06:00:00', '2024-08-09 08:30:00'),
('VN2', 'Nautical St - White water', NULL, NULL),
('SP4', 'South Paris Arena 4', NULL, NULL),
('NPA', 'North Paris Arena', '2024-07-27 13:30:00', '2024-08-08 15:30:00'),
('TAH', 'Teahupo\'o, Tahiti', NULL, NULL),
('LC3', 'La Concorde 3', NULL, NULL),
('MAM', 'Marseille Marina', '2024-07-28 09:00:00', '2024-08-08 17:00:00'),
('ELA', 'Elancourt Hill', '2024-07-28 12:00:00', '2024-07-29 14:30:00'),
('LC2', 'La Concorde 2', NULL, NULL),
('LC1', 'La Concorde 1', NULL, NULL),
('TRO', 'Trocad�ro', '2024-08-01 05:30:00', '2024-08-07 08:50:00'),
('LGN', 'Le Golf National', NULL, NULL),
('VE2', 'BMX Stadium', NULL, NULL),
('LBO', 'Le Bourget Climbing Venue', NULL, NULL),
('VE1', 'National Velodrome', NULL, NULL),
('LC4', 'La Concorde 4', NULL, NULL),
('ZAA', 'Fake Venue AA', NULL, NULL),
('ZAB', 'Fake Venue AB', NULL, NULL),
('ZAC', 'Fake Venue AC', NULL, NULL),
('ZAD', 'Fake Venue AD', NULL, NULL),
('ZAE', 'Fake Venue AE', NULL, NULL),
('ZAF', 'Fake Venue AF', NULL, NULL),
('ZAG', 'Fake Venue AG', NULL, NULL),
('ZAH', 'Fake Venue AH', NULL, NULL),
('ZAI', 'Fake Venue AI', NULL, NULL),
('ZAJ', 'Fake Venue AJ', NULL, NULL),
('ZAK', 'Fake Venue AK', NULL, NULL),
('ZAL', 'Fake Venue AL', NULL, NULL),
('ZAM', 'Fake Venue AM', NULL, NULL),
('ZAN', 'Fake Venue AN', NULL, NULL),
('ZAO', 'Fake Venue AO', NULL, NULL),
('ZAP', 'Fake Venue AP', NULL, NULL),
('ZAQ', 'Fake Venue AQ', NULL, NULL),
('ZAR', 'Fake Venue AR', NULL, NULL),
('ZAS', 'Fake Venue AS', NULL, NULL),
('ZAT', 'Fake Venue AT', NULL, NULL),
('ZAU', 'Fake Venue AU', NULL, NULL),
('ZAV', 'Fake Venue AV', NULL, NULL),
('ZAW', 'Fake Venue AW', NULL, NULL),
('ZAX', 'Fake Venue AX', NULL, NULL),
('ZAY', 'Fake Venue AY', NULL, NULL),
('ZAZ', 'Fake Venue AZ', NULL, NULL),
('ZBA', 'Fake Venue BA', NULL, NULL),
('ZBB', 'Fake Venue BB', NULL, NULL),
('ZBC', 'Fake Venue BC', NULL, NULL),
('ZBD', 'Fake Venue BD', NULL, NULL),
('ZBE', 'Fake Venue BE', NULL, NULL),
('ZBF', 'Fake Venue BF', NULL, NULL),
('ZBG', 'Fake Venue BG', NULL, NULL),
('ZBH', 'Fake Venue BH', NULL, NULL),
('ZBI', 'Fake Venue BI', NULL, NULL),
('ZBJ', 'Fake Venue BJ', NULL, NULL),
('ZBK', 'Fake Venue BK', NULL, NULL),
('ZBL', 'Fake Venue BL', NULL, NULL),
('ZBM', 'Fake Venue BM', NULL, NULL),
('ZBN', 'Fake Venue BN', NULL, NULL),
('ZBO', 'Fake Venue BO', NULL, NULL),
('ZBP', 'Fake Venue BP', NULL, NULL),
('ZBQ', 'Fake Venue BQ', NULL, NULL),
('ZBR', 'Fake Venue BR', NULL, NULL),
('ZBS', 'Fake Venue BS', NULL, NULL),
('ZBT', 'Fake Venue BT', NULL, NULL),
('ZBU', 'Fake Venue BU', NULL, NULL),
('ZBV', 'Fake Venue BV', NULL, NULL),
('ZBW', 'Fake Venue BW', NULL, NULL),
('ZBX', 'Fake Venue BX', NULL, NULL),
('ZBY', 'Fake Venue BY', NULL, NULL),
('ZBZ', 'Fake Venue BZ', NULL, NULL),
('ZCA', 'Fake Venue CA', NULL, NULL),
('ZCB', 'Fake Venue CB', NULL, NULL),
('ZCC', 'Fake Venue CC', NULL, NULL),
('ZCD', 'Fake Venue CD', NULL, NULL),
('ZCE', 'Fake Venue CE', NULL, NULL),
('ZCF', 'Fake Venue CF', NULL, NULL),
('ZCG', 'Fake Venue CG', NULL, NULL),
('ZCH', 'Fake Venue CH', NULL, NULL),
('ZCI', 'Fake Venue CI', NULL, NULL),
('ZCJ', 'Fake Venue CJ', NULL, NULL),
('ZCK', 'Fake Venue CK', NULL, NULL),
('ZCL', 'Fake Venue CL', NULL, NULL),
('ZCM', 'Fake Venue CM', NULL, NULL),
('ZCN', 'Fake Venue CN', NULL, NULL),
('ZCO', 'Fake Venue CO', NULL, NULL),
('ZCP', 'Fake Venue CP', NULL, NULL),
('ZCQ', 'Fake Venue CQ', NULL, NULL),
('ZCR', 'Fake Venue CR', NULL, NULL),
('ZCS', 'Fake Venue CS', NULL, NULL),
('ZCT', 'Fake Venue CT', NULL, NULL),
('ZCU', 'Fake Venue CU', NULL, NULL),
('ZCV', 'Fake Venue CV', NULL, NULL),
('ZCW', 'Fake Venue CW', NULL, NULL),
('ZCX', 'Fake Venue CX', NULL, NULL),
('ZCY', 'Fake Venue CY', NULL, NULL),
('ZCZ', 'Fake Venue CZ', NULL, NULL),
('ZDA', 'Fake Venue DA', NULL, NULL),
('ZDB', 'Fake Venue DB', NULL, NULL),
('ZDC', 'Fake Venue DC', NULL, NULL),
('ZDD', 'Fake Venue DD', NULL, NULL),
('ZDE', 'Fake Venue DE', NULL, NULL),
('ZDF', 'Fake Venue DF', NULL, NULL),
('ZDG', 'Fake Venue DG', NULL, NULL),
('ZDH', 'Fake Venue DH', NULL, NULL),
('ZDI', 'Fake Venue DI', NULL, NULL),
('ZDJ', 'Fake Venue DJ', NULL, NULL),
('ZDK', 'Fake Venue DK', NULL, NULL),
('ZDL', 'Fake Venue DL', NULL, NULL),
('ZDM', 'Fake Venue DM', NULL, NULL),
('ZDN', 'Fake Venue DN', NULL, NULL),
('ZDO', 'Fake Venue DO', NULL, NULL),
('ZDP', 'Fake Venue DP', NULL, NULL),
('ZDQ', 'Fake Venue DQ', NULL, NULL),
('ZDR', 'Fake Venue DR', NULL, NULL),
('ZDS', 'Fake Venue DS', NULL, NULL),
('ZDT', 'Fake Venue DT', NULL, NULL),
('ZDU', 'Fake Venue DU', NULL, NULL),
('ZDV', 'Fake Venue DV', NULL, NULL),
('ZDW', 'Fake Venue DW', NULL, NULL),
('ZDX', 'Fake Venue DX', NULL, NULL),
('ZDY', 'Fake Venue DY', NULL, NULL),
('ZDZ', 'Fake Venue DZ', NULL, NULL),
('ZEA', 'Fake Venue EA', NULL, NULL),
('ZEB', 'Fake Venue EB', NULL, NULL),
('ZEC', 'Fake Venue EC', NULL, NULL),
('ZED', 'Fake Venue ED', NULL, NULL),
('ZEE', 'Fake Venue EE', NULL, NULL),
('ZEF', 'Fake Venue EF', NULL, NULL),
('ZEG', 'Fake Venue EG', NULL, NULL),
('ZEH', 'Fake Venue EH', NULL, NULL),
('ZEI', 'Fake Venue EI', NULL, NULL),
('ZEJ', 'Fake Venue EJ', NULL, NULL),
('ZEK', 'Fake Venue EK', NULL, NULL),
('ZEL', 'Fake Venue EL', NULL, NULL),
('ZEM', 'Fake Venue EM', NULL, NULL),
('ZEN', 'Fake Venue EN', NULL, NULL),
('ZEO', 'Fake Venue EO', NULL, NULL),
('ZEP', 'Fake Venue EP', NULL, NULL),
('ZEQ', 'Fake Venue EQ', NULL, NULL),
('ZER', 'Fake Venue ER', NULL, NULL),
('ZES', 'Fake Venue ES', NULL, NULL),
('ZET', 'Fake Venue ET', NULL, NULL),
('ZEU', 'Fake Venue EU', NULL, NULL),
('ZEV', 'Fake Venue EV', NULL, NULL),
('ZEW', 'Fake Venue EW', NULL, NULL),
('ZEX', 'Fake Venue EX', NULL, NULL),
('ZEY', 'Fake Venue EY', NULL, NULL),
('ZEZ', 'Fake Venue EZ', NULL, NULL),
('ZFA', 'Fake Venue FA', NULL, NULL),
('ZFB', 'Fake Venue FB', NULL, NULL),
('ZFC', 'Fake Venue FC', NULL, NULL),
('ZFD', 'Fake Venue FD', NULL, NULL),
('ZFE', 'Fake Venue FE', NULL, NULL),
('ZFF', 'Fake Venue FF', NULL, NULL),
('ZFG', 'Fake Venue FG', NULL, NULL),
('ZFH', 'Fake Venue FH', NULL, NULL),
('ZFI', 'Fake Venue FI', NULL, NULL),
('ZFJ', 'Fake Venue FJ', NULL, NULL),
('ZFK', 'Fake Venue FK', NULL, NULL),
('ZFL', 'Fake Venue FL', NULL, NULL),
('ZFM', 'Fake Venue FM', NULL, NULL),
('ZFN', 'Fake Venue FN', NULL, NULL),
('ZFO', 'Fake Venue FO', NULL, NULL),
('ZFP', 'Fake Venue FP', NULL, NULL),
('ZFQ', 'Fake Venue FQ', NULL, NULL),
('ZFR', 'Fake Venue FR', NULL, NULL),
('ZFS', 'Fake Venue FS', NULL, NULL),
('ZFT', 'Fake Venue FT', NULL, NULL),
('ZFU', 'Fake Venue FU', NULL, NULL),
('ZFV', 'Fake Venue FV', NULL, NULL),
('ZFW', 'Fake Venue FW', NULL, NULL),
('ZFX', 'Fake Venue FX', NULL, NULL),
('ZFY', 'Fake Venue FY', NULL, NULL),
('ZFZ', 'Fake Venue FZ', NULL, NULL),
('ZGA', 'Fake Venue GA', NULL, NULL),
('ZGB', 'Fake Venue GB', NULL, NULL),
('ZGC', 'Fake Venue GC', NULL, NULL),
('ZGD', 'Fake Venue GD', NULL, NULL),
('ZGE', 'Fake Venue GE', NULL, NULL),
('ZGF', 'Fake Venue GF', NULL, NULL),
('ZGG', 'Fake Venue GG', NULL, NULL),
('ZGH', 'Fake Venue GH', NULL, NULL),
('ZGI', 'Fake Venue GI', NULL, NULL),
('ZGJ', 'Fake Venue GJ', NULL, NULL),
('ZGK', 'Fake Venue GK', NULL, NULL),
('ZGL', 'Fake Venue GL', NULL, NULL),
('ZGM', 'Fake Venue GM', NULL, NULL),
('ZGN', 'Fake Venue GN', NULL, NULL),
('ZGO', 'Fake Venue GO', NULL, NULL),
('ZGP', 'Fake Venue GP', NULL, NULL),
('ZGQ', 'Fake Venue GQ', NULL, NULL),
('ZGR', 'Fake Venue GR', NULL, NULL),
('ZGS', 'Fake Venue GS', NULL, NULL),
('ZGT', 'Fake Venue GT', NULL, NULL),
('ZGU', 'Fake Venue GU', NULL, NULL),
('ZGV', 'Fake Venue GV', NULL, NULL),
('ZGW', 'Fake Venue GW', NULL, NULL),
('ZGX', 'Fake Venue GX', NULL, NULL),
('ZGY', 'Fake Venue GY', NULL, NULL),
('ZGZ', 'Fake Venue GZ', NULL, NULL),
('ZHA', 'Fake Venue HA', NULL, NULL),
('ZHB', 'Fake Venue HB', NULL, NULL),
('ZHC', 'Fake Venue HC', NULL, NULL),
('ZHD', 'Fake Venue HD', NULL, NULL),
('ZHE', 'Fake Venue HE', NULL, NULL),
('ZHF', 'Fake Venue HF', NULL, NULL),
('ZHG', 'Fake Venue HG', NULL, NULL),
('ZHH', 'Fake Venue HH', NULL, NULL),
('ZHI', 'Fake Venue HI', NULL, NULL),
('ZHJ', 'Fake Venue HJ', NULL, NULL),
('ZHK', 'Fake Venue HK', NULL, NULL),
('ZHL', 'Fake Venue HL', NULL, NULL),
('ZHM', 'Fake Venue HM', NULL, NULL),
('ZHN', 'Fake Venue HN', NULL, NULL),
('ZHO', 'Fake Venue HO', NULL, NULL),
('ZHP', 'Fake Venue HP', NULL, NULL),
('ZHQ', 'Fake Venue HQ', NULL, NULL),
('ZHR', 'Fake Venue HR', NULL, NULL),
('ZHS', 'Fake Venue HS', NULL, NULL),
('ZHT', 'Fake Venue HT', NULL, NULL),
('ZHU', 'Fake Venue HU', NULL, NULL),
('ZHV', 'Fake Venue HV', NULL, NULL),
('ZHW', 'Fake Venue HW', NULL, NULL),
('ZHX', 'Fake Venue HX', NULL, NULL),
('ZHY', 'Fake Venue HY', NULL, NULL),
('ZHZ', 'Fake Venue HZ', NULL, NULL),
('ZIA', 'Fake Venue IA', NULL, NULL),
('ZIB', 'Fake Venue IB', NULL, NULL),
('ZIC', 'Fake Venue IC', NULL, NULL),
('ZID', 'Fake Venue ID', NULL, NULL),
('ZIE', 'Fake Venue IE', NULL, NULL),
('ZIF', 'Fake Venue IF', NULL, NULL),
('ZIG', 'Fake Venue IG', NULL, NULL),
('ZIH', 'Fake Venue IH', NULL, NULL),
('ZII', 'Fake Venue II', NULL, NULL),
('ZIJ', 'Fake Venue IJ', NULL, NULL),
('ZIK', 'Fake Venue IK', NULL, NULL),
('ZIL', 'Fake Venue IL', NULL, NULL),
('ZIM', 'Fake Venue IM', NULL, NULL),
('ZIN', 'Fake Venue IN', NULL, NULL),
('ZIO', 'Fake Venue IO', NULL, NULL),
('ZIP', 'Fake Venue IP', NULL, NULL),
('ZIQ', 'Fake Venue IQ', NULL, NULL),
('ZIR', 'Fake Venue IR', NULL, NULL),
('ZIS', 'Fake Venue IS', NULL, NULL),
('ZIT', 'Fake Venue IT', NULL, NULL),
('ZIU', 'Fake Venue IU', NULL, NULL),
('ZIV', 'Fake Venue IV', NULL, NULL),
('ZIW', 'Fake Venue IW', NULL, NULL),
('ZIX', 'Fake Venue IX', NULL, NULL),
('ZIY', 'Fake Venue IY', NULL, NULL),
('ZIZ', 'Fake Venue IZ', NULL, NULL),
('ZJA', 'Fake Venue JA', NULL, NULL),
('ZJB', 'Fake Venue JB', NULL, NULL),
('ZJC', 'Fake Venue JC', NULL, NULL),
('ZJD', 'Fake Venue JD', NULL, NULL),
('ZJE', 'Fake Venue JE', NULL, NULL),
('ZJF', 'Fake Venue JF', NULL, NULL),
('ZJG', 'Fake Venue JG', NULL, NULL),
('ZJH', 'Fake Venue JH', NULL, NULL),
('ZJI', 'Fake Venue JI', NULL, NULL),
('ZJJ', 'Fake Venue JJ', NULL, NULL),
('ZJK', 'Fake Venue JK', NULL, NULL),
('ZJL', 'Fake Venue JL', NULL, NULL),
('ZJM', 'Fake Venue JM', NULL, NULL),
('ZJN', 'Fake Venue JN', NULL, NULL),
('ZJO', 'Fake Venue JO', NULL, NULL),
('ZJP', 'Fake Venue JP', NULL, NULL),
('ZJQ', 'Fake Venue JQ', NULL, NULL),
('ZJR', 'Fake Venue JR', NULL, NULL),
('ZJS', 'Fake Venue JS', NULL, NULL),
('ZJT', 'Fake Venue JT', NULL, NULL),
('ZJU', 'Fake Venue JU', NULL, NULL),
('ZJV', 'Fake Venue JV', NULL, NULL),
('ZJW', 'Fake Venue JW', NULL, NULL),
('ZJX', 'Fake Venue JX', NULL, NULL),
('ZJY', 'Fake Venue JY', NULL, NULL),
('ZJZ', 'Fake Venue JZ', NULL, NULL),
('ZKA', 'Fake Venue KA', NULL, NULL),
('ZKB', 'Fake Venue KB', NULL, NULL),
('ZKC', 'Fake Venue KC', NULL, NULL),
('ZKD', 'Fake Venue KD', NULL, NULL),
('ZKE', 'Fake Venue KE', NULL, NULL),
('ZKF', 'Fake Venue KF', NULL, NULL),
('ZKG', 'Fake Venue KG', NULL, NULL),
('ZKH', 'Fake Venue KH', NULL, NULL),
('ZKI', 'Fake Venue KI', NULL, NULL),
('ZKJ', 'Fake Venue KJ', NULL, NULL),
('ZKK', 'Fake Venue KK', NULL, NULL),
('ZKL', 'Fake Venue KL', NULL, NULL),
('ZKM', 'Fake Venue KM', NULL, NULL),
('ZKN', 'Fake Venue KN', NULL, NULL),
('ZKO', 'Fake Venue KO', NULL, NULL),
('ZKP', 'Fake Venue KP', NULL, NULL),
('ZKQ', 'Fake Venue KQ', NULL, NULL),
('ZKR', 'Fake Venue KR', NULL, NULL),
('ZKS', 'Fake Venue KS', NULL, NULL),
('ZKT', 'Fake Venue KT', NULL, NULL),
('ZKU', 'Fake Venue KU', NULL, NULL),
('ZKV', 'Fake Venue KV', NULL, NULL),
('ZKW', 'Fake Venue KW', NULL, NULL),
('ZKX', 'Fake Venue KX', NULL, NULL),
('ZKY', 'Fake Venue KY', NULL, NULL),
('ZKZ', 'Fake Venue KZ', NULL, NULL);

